### PR TITLE
vendoring and cleanup

### PR DESCRIPTION
**Pull request by vikwick**
Found that I needed to update ~4 dependencies and change `gopkg.in/gin-gonic/gin.v1` to `github.com/gin-gonic/gin` for this to install correctly. This locks down those dependencies and fixes a couple of branding inconsistencies in the docs.

### CODE REVIEW

**Comment by turtlemonvh** [comment]
@vikwick I'm new to `dep`, but running your branch locally I am seeing this

```
$ go build ./tnnlr/main.go
# github.com/turtlemonvh/tnnlr/vendor/github.com/timjchin/unpuzzled
vendor/github.com/timjchin/unpuzzled/variable_config.go:82:8: undefined: toml.TomlTree
```

Perhaps `dep` didn't look for dependencies in the `tnnl` subdirectory when initializing?

Also, I'll set up CI for this project tomorrow so we can at least check that this is building on a clean system!

**Comment by turtlemonvh** [comment]
We'll need to update the CI stuff like this to get it to work with dep:
https://github.com/golang/dep/issues/1275

**Comment by turtlemonvh** [comment]
@vikwick I did a little digging, and tag `1.2` (097fbae) is missing a change on the master branch that makes the code work with newer versions of the toml library:
https://github.com/timjchin/unpuzzled/commits/master

That dependency needs to be updated to point to the latest master instead.

**Comment by turtlemonvh** [comment]
I think we're gtg now.  I'll merge and just fix whatever remains on the master branch.  Thanks!

**Comment by vikwick** [comment]
Apologies, @turtlemonvh. Definitely a result of my nascent experience with `dep`. Thanks for resolving the issue and merging!

**Comment by turtlemonvh** [comment]
No worries @vikwick - thanks for the contribution.

**Pull request merged**
